### ISSUE TITLE
RPK weapon and Ammo 

### ISSUE THREAD

**Issue by fazmond** [DayZMod/Battleye-Filters#131]
my guys reported they are getting kicks for this also
RPK weapon and Ammo

**Comment by GeryonTom** [comment]
Can you provide an entry in the log?

**Comment by fazmond** [comment]
09.06.2015 19:21:35: PLAYER NAME (PLAYERIP) PLAYERGUID - #0 "RPK_74" 0:0

taken from addweaponcargo

**Comment by GeryonTom** [comment]
Run the following patch to convert the RPK over to the DZ version.  This should fix the SVK as well.

SET @instance = 0;

SET @from_str = '"RPK_74"';
SET @to_str = '"RPK74_DZ"';
UPDATE character_data
    SET Inventory = REPLACE(Inventory,@from_str,@to_str), Backpack = REPLACE(Backpack,@from_str,@to_str)
    WHERE InstanceID = @instance;
UPDATE object_data
    SET Inventory = REPLACE(Inventory,@from_str,@to_str)
    WHERE Instance = @instance;

SET @from_str = '"SVD"';
SET @to_str = '"SVD_DZ"';
UPDATE character_data
    SET Inventory = REPLACE(Inventory,@from_str,@to_str), Backpack = REPLACE(Backpack,@from_str,@to_str)
    WHERE InstanceID = @instance;
UPDATE object_data
    SET Inventory = REPLACE(Inventory,@from_str,@to_str)
    WHERE Instance = @instance;

**Comment by fazmond** [comment]
ok will do
