### ISSUE TITLE
CreateVehicle Restrictions issue

### ISSUE THREAD

**Issue by cikez** [DayZMod/Battleye-Filters#133]
A lot of my players are being kicked for the following createvehicle restrictions....

03.10.2015 18:14:38: EnglishMuffin (hiddenip) ab0f5dde834c99e39dac7966f8d195c7 - #0 "Fence_corrugated_plate" 15:83 [9716,13688,61]
03.10.2015 18:14:38: EnglishMuffin (hiddenip) ab0f5dde834c99e39dac7966f8d195c7 - #0 "Hhedgehog_concrete" 15:84 [9709,13689,61]

Any ideas?

**Comment by kichilron** [comment]
These have to do with the fact that you have custom stuff on your server ("Fence_corrugated_plate" / "Hhedgehog_concrete").

You may want to add those to your createVehicle exceptions in BattlEye.

**Comment by cikez** [comment]
Hmm, ok I am new to Battleye filters.. Will adding this:

!=Fence_corrugated_plate !=Hhedgehog_concrete

to the end of this line fix it?:

1 !(^DZ_|^z_|^WeaponHolder|Box|^Smoke|^Chem|^._40mm|_DZ$|^Trap) !=(SeaGull|SmallSecondary|HelicopterExplo(Small|Big)|Stash(Small|Medium)(|[1-4])|(|Dome)TentStorage(|[0-4])) !=(CZ_VestPouch_EP1|R_M136_AT|Wire_cat1) !=(JackDaniels|(Tin|Soda)Can|RoadFlare|WoodenArrowF|zZombie_Base|ParachuteWest|Grenade(_|HandTimed)(West|East)) !=(CMflareAmmo|Pipebomb) !=(WildBoar|Rabbit|Sheep|Goat|Hen|Cow0[1234]) !=Blood_Trail_DZ !^(Wooden|Metal)Fence !^WoodenGate_ !=(ShantyHouse(|Stage[2-7])|SurvivorWorkshop(|Stage2|[ABC]Stage[345])|WorkBench) !=explosive_bolt

**Comment by ebayShopper** [comment]
Yes.
