### ISSUE TITLE
Can I still use it now? How to trigger the rules set in txt?

### ISSUE THREAD

**Issue by yuboabc** [DayZMod/Battleye-Filters#135]
I added txt to the root directory of the battleye, but it didn't work. I didn't know how to trigger the set rules and didn't generate the corresponding log file.

**Comment by griha41** [comment]
> I added txt to the root directory of the battleye, but it didn't work. I didn't know how to trigger the set rules and didn't generate the corresponding log file.

Hey (again, it's Sid from DZ Forum).

Concept of BE filters is quite simple.
There's events (each event described in .txt file, expect scripts.txt)

The scripts.txt contains all script commands that's has a special restriction (by number at start of the line). You can read it here: https://forums.bohemia.net/forums/topic/131085-introducing-server-side-event-loggingblocking/
Restrictions (actions) list:
1 - Log detections to "scripts.log"
2 - Log detections to server console
3 - Log to both
4 - Kick for detections ("Script Restriction #X")
5 - Kick and log to .log file
6 - Kick and log to console
7 - Kick and log to both

The logic is like:

1 "createVehicle"
That line means that every command that contains function createVehicle will be loged to the console window.
When:
7 "createVehicle"
if server send command to client for createVehcle - client will be kicked from the server, and that information will be appended to consile window, scrips.log, and client got message: Battleye Scripts Restriction #1 (createVehicle)

Something like this, but be careful that approach not working in the DayZ Standalone, there's no such filters there!

**Comment by yuboabc** [comment]
THK very~
