### ISSUE TITLE
script restriction #205?

### ISSUE THREAD

**Issue by sharkiller** [DayZMod/Battleye-Filters#34]
i have a lot of kicks for this, related to setVehicleInit when you crash. is that normal? can be fixed?

```
04.07.2013 12:12:44: ciVic (190.135.XXX.XXX:2304) XXXXXXXXXXXXXXXXX - #205 "s select 2) + 1];
sleep 0.05;
























_v setVehicleInit format ["[this, %1, %2]spawn BIS_Effects_AirDestructionS"
```

**Comment by icomrade** [comment]
Are you sure it's happening to legit players? From what I can see the use of SVI is commented out in the BIS effects.

**Comment by sharkiller** [comment]
yes, is a small community and happend to all of them.

**Comment by facoptere** [comment]
It's well known. This can't be fixed.
You have to restart the server when this happen.
