### ISSUE TITLE
tanktrap bug

### ISSUE THREAD

**Issue by sharkiller** [DayZMod/Battleye-Filters#38]
Players kicked when build a tanktrap

09.07.2013 20:53:06: xxxxx (xxxxx) xxxxx - #140 "_id = 'ItemTankTrap' spawn player_build; r_action_count = r_action_count + 1;;"
09.07.2013 20:54:06: xxxxx (xxxxx) xxxxx- #140 "_id = 'ItemTankTrap' spawn player_build; r_action_count = r_action_count + 1;;"

https://github.com/DayZMod/DayZ-Source/blob/Release_1.7.7.1/SQF/dayz_code/Configs/CfgMagazines/Deployable.hpp#L56

**Comment by facoptere** [comment]
precisely it was a call compile format in dayz_code/compile/ui_selectSlot.sqf
I updated the filter.
