### ISSUE TITLE
Script Restriction #61 since last scripts.txt update

### ISSUE THREAD

**Issue by kr4uzi** [DayZMod/Battleye-Filters#51]
Hello,
everytime you rejoin the game once going back to the lobby (connect to server->go into lobby->join game->abort->lobby->join game) you get kicked with restriction #61. This also happens e.g. when you die. The only fix is the shut down your game completely (going back to the server browser does not help).

**Comment by kr4uzi** [comment]
some additional info: since the last scripts.txt update the logs get spammed with this messages:
_v setVehicleInit format ["[this, %1, %2]spawn BIS_Effects_AirDestructionS"
06.09.2013 22:17:31: plr (ipport) guid - #61 "s select 2) + 1];
sleep 0.05;
23 new lines

hope this gets fixed soon

**Comment by facoptere** [comment]
it's an arma bug. You need to restart your server.
this will be fixed in next version.

**Comment by kr4uzi** [comment]
yep restarting fixes this.
