### ISSUE TITLE
#329 kick when hitting zombies with a vehicle

### ISSUE THREAD

**Issue by wriley** [DayZMod/Battleye-Filters#56]
I think the fix is:
5 zombie !zombieSpawn !ZombieStandingAttack !ZombieFeed2 !ZombieFeed1 !VehHandleDam

but still testing

**Comment by facoptere** [comment]
already fixed since several hours.

**Comment by wriley** [comment]
Which commit fixed this?

**Comment by facoptere** [comment]
3ad50b3cd65eb645a99e144c0c7242f7c03016ac

**Comment by wriley** [comment]
That doesn't address getting kicked by vehicle damage when hitting a zombie, does it?

This is what I see in the log:
Value Restriction #329 "PVDZ_send" = [<NULL-object>,"VehHandleDam",[<NULL-object>,"wheel_2_3_steering",0.2,<NULL-object>,"zombie"]]

**Comment by facoptere** [comment]
ah
I think I will remove this line. It's not a relevant pattern.

**Comment by wriley** [comment]
I'm not that familiar with BattleEye filters so let me know what information I can provide to help. Players are getting kicked when hitting zombies in a vehicle. Adding !VehHandleDam to the zombie kick line seemed to fix but may not be the correct solution.

Value Restriction #329 "PVDZ_send" = [<NULL-object>,"VehHandleDam",[<NULL-object>,"wheel_2_1_steering",0.1,<NULL-object>,"zombie"]]
Value Restriction #329 "PVDZ_send" = [<NULL-object>,"VehHandleDam",[<NULL-object>,"wheel_2_3_steering",0.2,<NULL-object>,"zombie"]]
Value Restriction #329 "PVDZ_send" = [<NULL-object>,"VehHandleDam",[<NULL-object>,"wheel_1_2_steering",0.4,<NULL-object>,"zombie"]]

**Comment by facoptere** [comment]
The simpler solution is to delete "zombie" pattern, In 1.8, this keyword is used everywhere as simple argument, not only in function name (as in 1771). So we don't control it anymore. 

don't worry, it was not a so useful pattern.
