### ISSUE TITLE
Remoteexec.txt Line#38

### ISSUE THREAD

**Issue by k4n30** [DayZMod/Battleye-Filters#6]
Error on line 38 in remoteexec

Is currently: 

!="this enableSimulation false;this allowDammage false;this disableAI FSM;this disableAI ANIM;this disableAI MOVE;"

should be:
!="this enableSimulation false;this allowDammage false;this disableAI 'FSM';this disableAI 'ANIM';this disableAI 'MOVE';"

note the ' ' around the capitalised words. This causes players to be kicked randomly

**Comment by facoptere** [comment]
thanks, it's fixed now.
BTW this rule is "1" so it does not kick players. This is used for logging only.

**Comment by k4n30** [comment]
:) Sorry bout the kicking comment, I use pyBEscanner on strict so it was actually banning people. I'm so used to having to change it to kick when commenting I didn't even check
