### ISSUE TITLE
New restrictions removed all tents

### ISSUE THREAD

**Issue by FramedYannick** [DayZMod/Battleye-Filters#8]
hy

on our server, all the tents and vehicles are not showing up annymore...
we had some extra custom vehicles, so i do not really care those are gone,
but the legit vehicles and all the tents are not there :s 

They are still in the database, and showing up in tsw, but they are not ingame...

do u know a solution for this?

thanks

**Comment by facoptere** [comment]
It's not related to BE filters.
Please copy/paste your request to https://github.com/DayZMod/DayZ/issues
